let word = 'hello';
console.log(word);
alert(word);
document.write(`<div>${word}</div>`);
let term = 'owu';
console.log(term);
alert(term);
document.write(`<div>${term}</div>`);
let domain = 'com.ua';
console.log(domain);
alert(domain);
document.write(`<div>${domain}</div>`);
let symb0 = (5/5);
console.log(symb0);
let symb1 = (5+5);
console.log(symb1);
let symb2 = (1-1000);
console.log(symb2);
let symb3 = (100+23);
console.log(symb3);
let pi = 3.14;
console.log(pi);
let symb4 = (2+0.7);
console.log(symb4);
let symb5 =(8*2);
console.log(symb5);
console.log(1<2);
console.log(1===2);

let firstName = 'Nazar';
let middleName = 'Zinoviyovich';
let lastName = 'Gorodyskyi';
let person = (lastName + ' ' + firstName + ' ' + middleName);
console.log(person);

let name = prompt('Мене звати', 'Nazar');
let secondname = prompt('По-батькові', 'Зіновійович');
let age = prompt ('Мені', '30 років');

let a = 100;
console.log(typeof a);
let b ='100';
console.log(typeof b);
let c = true;
console.log(typeof c);

console.log(5<6);
console.log(5===6);
console.log(5>=6);
console.log(5>=6);
console.log(10<=10);
console.log(10>=10);
let false1 = 10!==10;
console.log(false1);
let false2 = 10<10;
console.log(false2);
let false3 = 10>10;
console.log(false3);
console.log(123==='123');
console.log(123!=='123');